/*
	'GeckoBug1.idl' by Claude SIMON (http://zeusw.org/).

	 This file is part of 'GeckoBug1' software.

    'eGeckoCOM' is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    'GeckoBug1' is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with 'GeckoBug1'.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "nsISupports.idl"

[scriptable, uuid(18dce255-172e-4661-8899-7b4a85a521b1)]
interface IGeckoBug1
: nsISupports
{
	void Test();
};