/*
	'egeckocom.idl' by Claude SIMON (http://zeusw.org/).

	 This file is part of 'eGeckoCOM' software.

    'eGeckoCOM' is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    'eGeckoCOM' is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with 'eGeckoCOM'.  If not, see <http://www.gnu.org/licenses/>.
*/

// $Id$

#include "nsIDOMWindow.idl"
#include "nsICommandLine.idl"

[scriptable, uuid(07232fe0-fee4-11e0-be50-0800200c9a66)]
interface EIGeckoCOM
: nsISupports
{
	void Create(
		in string ComponentId,
		in string Language,
		out string ErrorMessage );
	void Retrieve(
		in string ComponentId,
		out string ErrorMessage );
	void Register(
		in nsIDOMWindow Window,
		out string ErrorMessage );	
	void Stop(
		in nsICommandLine CommandLine,
		out string ErrorMessage );
	void Terminate( out string ErrorMessage );
	void HandlePseudoEvent(
		in nsIDOMElement Element,
		in string Parameter,
		out string ErrorMessage );
	void Test( out string ErrorMessage );	// A des fins de deboguage uniquement.
};